#!/bin/sh /etc/rc.common

START=60
STOP=20

PIDFILE=/var/run/k3s.pid
EXEC="/usr/bin/k3s"

OPTS="$(uci_get k3s.globals.opts)"
[ "$(uci_get k3s.globals.root)" != "" ] && DATA="--data-dir $(uci_get k3s.globals.root)"

ensure_root_rshared() {
/bin/mount --make-rshared /
}

start() {

  ensure_root_rshared
  if [ "$(uci_get_state k3s.globals.type)" = "server" ];then
    if [ "$(uci_get_state k3s.globals.cluster)" != "1" ]; then
      uci_set k3s globals cluster 1
      uci_commit k3s
      OPTS="$OPTS --cluster-init"
    fi
    start-stop-daemon -S -b -x "$EXEC" -m -p "$PIDFILE" -- server $OPTS --log /var/log/k3s $DATA
    logger "start-stop-daemon -S -b -x \"$EXEC\" -m -p \"$PIDFILE\" -- server $OPTS --log /var/log/k3s $DATA"
  fi
  if [ "$(uci_get_state k3s.globals.type)" = "agent" ]; then
    if [ "$(uci_get_state k3s.globals.name)" != "" ]; then
      OPTS="$OPTS --node-name $(uci_get_state k3s.globals.name)"
    else
      OPTS="$OPTS --with-node-id"
    fi
    start-stop-daemon -S -b -x "$EXEC" -m -p "$PIDFILE" -- agent  $OPTS --log /var/log/k3s $DATA && \
    logger "start-stop-daemon -S -b -x \"$EXEC\" -m h-p \"$PIDFILE\" -- agent $OPTS --log /var/log/k3s $DATA"
  fi
}

stop() {
  start-stop-daemon -K -p "$PIDFILE"
}
